apiVersion: v1
kind: Pod
metadata:
  name: nginx1
spec:
  volumes:
  - name: my-nfs
    persistentVolumeClaim:
      claimName: pvc1  # created above
  containers:
  - image: nginx
    name: nginx-container
    volumeMounts:
      - mountPath: "/demo_mnt"  # you can customize mountPath
        name: my-nfs  # define in volumes